!!com.suiyueyule.abtest.config.ConfigManage
abTestConfig:
  layers:
    RECOMMEND_ITEM:
      bucketList:
      - bucketList: !!set {0: null}
        classTag: com.suiyueyule.abtest.algorithm.impl.DefaultRecommendItemServiceImpl
        paramList: {PAMA: '000000', PAMB: '000001'}
        plan: 201806A
      - bucketList: !!set {1: null}
        classTag: com.suiyueyule.abtest.algorithm.impl.CFRecommendItemServiceImpl
        paramList: {PAMA: '000000', PAMB: '000001'}
        plan: 201806B
      bucketSize: 2
      factor: RECOMMEND_ITEM
    RECOMMEND_ITEM_RELEVANT:
      bucketList:
      - bucketList: !!set {0: null}
        classTag: com.suiyueyule.abtest.algorithm.impl.DefaultRecommendItemRelevantServiceImpl
        paramList: {PAMA: '000000', PAMB: '000001'}
        plan: 201806A
      - bucketList: !!set {1: null}
        classTag: com.suiyueyule.abtest.algorithm.impl.CFRecommendItemRelevantServiceImpl
        paramList: {PAMA: '000000', PAMB: '000001'}
        plan: 201806B
      bucketSize: 2
      factor: RECOMMEND_ITEM_RELEVANT
recommendRedisConfig: {auth: '', connectionTimeout: 1200, dbIndex: 0, host: localhost,
  port: 6379, useSSL: false}
