!!com.suiyueyule.abtest.config.ConfigManage
abTestConfig:
  layers:
    RECOMMEND_ITEM:
      bucketList:
      - bucketList: !!set {0: null}
        paramList: {RECOMMEND_2008_01: '000000'}
        plan: '201806A'
        classTag: 'com.suiyueyule.abtest.algorithm.impl.CFRecommendItemServiceImpl'
      - bucketList: !!set {1: null}
        paramList: {RECOMMEND_2009_02: '000001'}
        plan: '201806B'
        classTag: 'com.suiyueyule.abtest.algorithm.impl.DefaultRecommendItemServiceImpl'
      bucketSize: 2
      factor: RECOMMEND_ITEM
    RECOMMEND_ITEM_RELEVANT:
      bucketList:
      - bucketList: !!set {0: null}
        paramList: {UI_2018_02: '000001'}
        plan: '201806A'
        classTag: 'com.suiyueyule.abtest.algorithm.impl.CFRecommendItemRelevantServiceImpl'
      - bucketList: !!set {1: null}
        paramList: {UI_2017_02: '000001'}
        plan: '201806B'
        classTag: 'com.suiyueyule.abtest.algorithm.impl.DefaultRecommendItemRelevantServiceImpl'
      bucketSize: 2
      factor: RECOMMEND_ITEM_RELEVANT